recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LfiqgQAAAAAAPckm2aX4vBr5S7ZuwEjMqVPwVb9"
	privateKey = "6LfiqgQAAAAAAKwHoux9SVZgNcZUIv9IicCAjbyk"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = false

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}